### ISSUE TITLE
custom colormaps for `ctmr_gauss_plot`

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#3]
Currently, `ctmr_gauss_plot` expects a string for a colormap, and does not accept an actual colormap object as is standard in mpl. I also tried creating a colormap and registering it with mpl and then using the string, but that didn't work either. Looking at the code didn't help much.. Is there any way of using a custom colormap with `ctmr_gauss_plot`?

**Comment by libertyh** [comment]
We implemented it this way because of mayavi's mlab colormap, which is specified as a string.  I did find this on the mayavi help about specifying a specific colormap: http://docs.enthought.com/mayavi/mayavi/auto/example_custom_colormap.html#example-custom-colormap
We could probably add this functionality by allowing the user to pass in either a string or a colormap object, and process as appropriate.

**Comment by libertyh** [comment]
Ben added this functionality, now you can pass either a string or a matplotlib.colors.LinearSegmentedColormap to ctmr_gauss_plot.py
