### ISSUE TITLE
I would like to be able to pass in elecmatrix to get_surface_warp.

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#7]
I don't have write permissions to the subject directory, but I'd like to be able to still compute surface warps. I'm planning on adding freeCoG.compute_surface_warp, which will be called by get_surface_warp and will take elecmatrix. Is that ok?

**Comment by libertyh** [comment]
Yes, I assume you mean take the contents of get_surface_warp() and turn that into a separate function that takes the elecmatrix.  Unfortunately you may also need write permissions in the subject directory to do this, because it writes out some intermediate label files that are used in the warping.  So for your purposes, maybe you'd want to add an output directory for the label intermediate files used by `mri_label2label`.

**Comment by bendichter** [comment]
yup, that's what I meant. And thanks for the tip!
