### ISSUE TITLE
patient.plot_brain() output

### ISSUE THREAD

**Issue by bendichter** [ChangLabUcsf/img_pipe#9]
I noticed that `patient.plot_brain()` outputs the `mayavi.mlab` module as the third element of the output tuple. This isn't causing any bugs, it's just kinda strange to output a module. Is that on purpose?

**Comment by libertyh** [comment]
It's helpful to have if you decide not to show the plot immediately and wish to make changes to the mesh or electrode properties before displaying.  For example, you could do the following to make the plot_brain call and then modify attributes after the fact:

`mesh, points, mlab = patient.plot_brain(showfig=False, helper_call=True)`
`mesh.actor.property.opacity = 0.4`
`mlab.view(azimuth=90)`
`mlab.show()`

Perhaps this is sort of an edge case anyway, because you should probably just use the underlying functions (e.g. el_add) if you want to really customize the plot.  But it was intentional!

**Comment by bendichter** [comment]
It looks like mesh is used to customize the properties in this case, not
mlab. Mlab is used to change the view angle though. It seems analogous to
returning pyplot with every plot.
